### ISSUE TITLE
Maintained versions of documentation for i18n support

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx-unsupported/edx-documentation#2002] opened 2022-01-06 19:42 UTC
If the documentation changes, the work towards i18n becomes obsolete. If versions of the documentation are maintained, then the Transifex Working group can focus on translating a version of the documentation without losing their progress.

**Comment by Carlos-Muniz** [comment] 2022-01-06 19:43
@sarina

**Comment by sarina** [comment] 2022-01-06 21:24
👍🏻 

May be worthwhile to mention that the versions should be tied to the named releases (so we'd have a Maple doc, a Nutmeg doc, etc)

**Comment by feanil** [comment] 2022-01-31 16:00
Closing as a duplicate of https://github.com/openedx/docs.openedx.org/issues/874

**Closed as completed by feanil** 2022-01-31 16:00 UTC
